# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# TODO(setup): Typically the course number, "DEPT XXX". it appears on nearly every page. Keep it short. :)
title: Data 8
# TODO:(setup): This should be the extended title of your course. e.g. "Introduction to Data Science"
tagline: Foundations of Data Science
description: A modern, highly customizable, responsive Jekyll template for course websites
# TODO(template): this should be built from the staff list...
author: Edwin Vargas Navarro and Brandon Su
# You should use either light or dark as the theme.
color_scheme: light

# TODO(setup): Set this to the semester, e.g. /sp24, (faXX / spXX / suXX / wiXX )
baseurl: '/fa24' # the subpath of your site, which should just be the semester.
# TODO(setup): Set this to your course's domain
url: 'https://www.data8.org' # the hostname & protocol for your site, e.g. http://example.com

# Course variables
# Course variables can appear in various places around the website, if something isn't used leave it blank.
# TODO(setup): Set all of these course variables
course: Data 8
course_email: data8@berkeley.edu
gradescope_course_id: 123456 # you can find this in the Gradescope URL after /courses
bcourses_course_id: 123456 # Same as above, but for bCourses. Leave blank if not in use...
ed_course_id: 123456 # Again, same as above.
sememster: fa24 # set for the current seemester
# This should be one of eecs, dsus, stat
# (Future) This will control some footer text, and later custom styling.
course_department: dsus
logo: "/data8logo.png"
current_week: 2
# This should be the page of all class archives
# Typically just / for DS courses (with a visible index page), or /archives if you're hosting your own, or a link to the inst.eecs page
# If you have no archive page, comment this line out or leave blank.
class_archive_path: /

# TODO(setup): Set these auxiliary links as you wish - they show up on the top right
aux_links:
  # TODO(template): Move this to be built-in.
  # Ed:
  #   - 'https://edstem.org/us/courses/64093/discussion/'
  OH Queue:
    - 'https://oh.data8.org/'
  Textbook:
    - 'https://inferentialthinking.com/chapters/intro.html'
  Extensions:
    - 'https://docs.google.com/forms/d/e/1FAIpQLSc2CSE_Ie_TR0r7lV7-JX0zNagoJ08t-EAK48iCAc3rVgHIXw/viewform'

# Collections for website data
collections:
  staffers:
    sort_by: name
  modules:
  schedules:
  announcements:
  labs:
    output: true
    permalink: /:collection/:path/
  hw:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/

# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: labs
    values:
      layout: lab
      nav_exclude: true
  - scope:
      path: ''
      type: hw
    values:
      layout: hw
      nav_exclude: true
  - scope:
      path: ''
      type: projects
    values:
      layout: project
      nav_exclude: true
  - scope:
      path: '_staffers'
      type: staffers
    values:
      layout: staffer
      height: 300
      subpath: '/assets/images/'
      width: 300
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

######################################################################
# Just the Docs / Berkeley Class Site Common Config
# Options below here will likely not need to be configured..
######################################################################
# TODO(template): CSS compilations. Handle warnings...
sass:
  style: expanded
  sass_dir: _sass
  sourcemap: always
  quiet_deps: true
  verbose: false

# The sitemap **must** be enabled. It's published as /baseurl/sitemap.xml
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache

# Theme settings
theme: just-the-docs
search_enabled: true
heading_anchors: true
permalink: pretty

## Footer Content.
# You should probably not change these, but may add to footer_content if necessary.
# Replace `true` with any additional HTML that you would like to add.
# Footer *must* included the accessibility text defined in footer_custom.html
footer_content: true
back_to_top: true
back_to_top_text: "Back to Top"
last_edit_timestamp: true
last_edit_time_format: '%m %d, %Y at %H:%M'

# Compilation settings used by compress-html plugin:
# https://github.com/penibelst/jekyll-compress-html/tree/v3.2.0?tab=readme-ov-file
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Native Jeykll build options
# You likely shouldn't need to touch these, but they are documented here just in case.
# https://jekyllrb.com/docs/configuration/options/

# This makes it easier when pushing to a static directory.
# The default false removes files in that directory, which is useful for when you unpublish pages.
# keep_files: false

# Likely not necessary, but a google default for Berkeley
timezone: America/Los_Angeles

# Note: dotfiles are excluded by default. .htaccess is included as a common case.
include:
  - LICENSE
  - .htaccess
  - robots.txt

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md
  - CONTRIBUTING.md
  - tmp/
  - spec/
  - docs/
  - node_modules/

links:
  hw:
    hw01: "[Homework 01](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-fa24&urlpath=tree%2Fmaterials-fa24%2Fhw%2Fhw01%2Fhw01.ipynb)"
    hw02: "Homework 02"
    hw03: "Homework 03"
    hw04: "Homework 04"
    hw05: "Homework 05"
    hw06: "Homework 06"
    hw07: "Homework 07"
    hw08: "Homework 08"
    hw09: "Homework 09"
    hw10: "Homework 10"
    hw11: "Homework 11"
    hw12: "Homework 12"
    hw13: "Homework 13"
  lab:
    lab01: "[Lab 01](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-fa24&branch=main&urlpath=tree%2Fmaterials-fa24%2Flab%2Flab01%2Flab01.ipynb)"
    lab02: "Lab 02"
    lab03: "Lab 03"
    lab04: "Lab 04"
    lab05: "Lab 05"
    lab06: "Lab 06"
    lab07: "Lab 07"
    lab08: "Lab 08"
    lab09: "Lab 09"
    lab10: "Lab 10"
  wksht:
    wksht01: "[Lab 01 Worksheet](https://drive.google.com/file/d/1SxtXURV9UabpSOtQDvRXy9qb6DxkSBF9/view?usp=sharing)"
    wksht02: ""
    wksht03: ""
    wksht04: ""
    wksht05: ""
    wksht06: ""
    wksht07: ""
    wksht08: ""
    wksht09: ""
    wksht10: ""
    wksht11: ""
    wksht12: ""
    wksht13: ""
  proj:
    proj1: "Project 1: World Population and Poverty"
    proj2: "Project 2: Climate"
    proj3: "Project 3: Classifying Movies"
  lec:
    demo:
      demo01: "&#8226; [Demo](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https://github.com/data-8/materials-fa24&urlpath=tree/materials-fa24/lec/lec01/lec01.ipynb&branch=main)"
      demo02: ""
      demo03: ""
      demo04: ""
      demo05: ""
      demo06: ""
      demo07: ""
      demo08: ""
      demo09: ""
      demo10: ""
      demo11: ""
      demo12: ""
      demo13: ""
      demo14: ""
      demo15: ""
      demo16: ""
      demo17: ""
      demo18: ""
      demo19: ""
      demo20: ""
      demo21: ""
      demo22: ""
      demo23: ""
      demo24: ""
      demo25: ""
      demo26: ""
      demo27: ""
      demo28: ""
      demo29: ""
      demo30: ""
      demo31: ""
      demo32: ""
      demo33: ""
      demo34: ""
      demo35: ""
      demo36: ""
      demo37: ""
      demo38: ""
      demo39: ""
      demo39: ""
    slides:
      slide01: "[Slides](https://docs.google.com/presentation/d/1Rg3tyM3b68n8Ko5OzsnnvXSbeP-HARD5WlLKUfXXCFk/edit?usp=sharing)"
      slide02: "[Slides](https://docs.google.com/presentation/d/1mpRbyc3oeT1vUFUs3zMztGVAjAGC7Gv9nweH3n8Zkz0/edit?usp=sharing)"
      slide03: ""
      slide04: ""
      slide05: ""
      slide06: ""
      slide07: ""
      slide08: ""
      slide09: ""
      slide10: ""
      slide11: ""
      slide12: ""
      slide13: ""
      slide14: ""
      slide15: ""
      slide16: ""
      slide17: ""
      slide18: ""
      slide19: ""
      slide20: ""
      slide21: ""
      slide22: ""
      slide23: ""
      slide24: ""
      slide25: ""
      slide26: ""
      slide27: ""
      slide28: ""
      slide29: ""
      slide30: ""
      slide31: ""
      slide32: ""
      slide33: ""
      slide34: ""
      slide35: ""
      slide36: ""
      slide37: ""
      slide38: ""
      slide39: ""
      slide40: ""
